import {
  AlertTriangle,
  Battery,
  Bell,
  Briefcase,
  Book as Broom,
  Calendar,
  Camera,
  Car,
  Clock,
  Cloud,
  Coffee,
  Download,
  Eye,
  EyeOff,
  Filter,
  Flag,
  Gamepad2,
  Gift,
  Headphones,
  Heart,
  HelpCircle,
  Home,
  Info,
  Laptop,
  Lock,
  type LucideIcon,
  Mail,
  MapPin,
  Mic,
  Moon,
  Music,
  Package,
  Pause,
  Phone,
  Play,
  Search,
  Settings,
  Share2,
  Shield,
  ShoppingBag,
  SkipForward,
  Sparkles,
  Star,
  Sun,
  Trash2,
  Unlock,
  Upload,
  Users,
  Utensils,
  Volume2,
  Wifi,
  Zap,
} from "lucide-react";

export const availableIcons: { icon: LucideIcon; name: string }[] = [
  { icon: Broom, name: "Broom" },
  { icon: Camera, name: "Camera" },
  { icon: Gift, name: "Gift" },
  { icon: Heart, name: "Heart" },
  { icon: Music, name: "Music" },
  { icon: Users, name: "Users" },
  { icon: Utensils, name: "Utensils" },
  { icon: Package, name: "Package" },
  { icon: Briefcase, name: "Briefcase" },
  { icon: Home, name: "Home" },
  { icon: Car, name: "Car" },
  { icon: Gamepad2, name: "Gamepad" },
  { icon: Laptop, name: "Laptop" },
  { icon: Coffee, name: "Coffee" },
  { icon: ShoppingBag, name: "Shopping" },
  { icon: Sparkles, name: "Sparkles" },
  { icon: Star, name: "Star" },
  { icon: Sun, name: "Sun" },
  { icon: Moon, name: "Moon" },
  { icon: Cloud, name: "Cloud" },
  { icon: Zap, name: "Zap" },
  { icon: Flag, name: "Flag" },
  { icon: Bell, name: "Bell" },
  { icon: Mail, name: "Mail" },
  { icon: Calendar, name: "Calendar" },
  { icon: Clock, name: "Clock" },
  { icon: MapPin, name: "MapPin" },
  { icon: Phone, name: "Phone" },
  { icon: Wifi, name: "Wifi" },
  { icon: Battery, name: "Battery" },
  { icon: Headphones, name: "Headphones" },
  { icon: Mic, name: "Mic" },
  { icon: Volume2, name: "Volume" },
  { icon: Play, name: "Play" },
  { icon: Pause, name: "Pause" },
  { icon: SkipForward, name: "Skip" },
  { icon: Settings, name: "Settings" },
  { icon: Download, name: "Download" },
  { icon: Upload, name: "Upload" },
  { icon: Share2, name: "Share" },
  { icon: Search, name: "Search" },
  { icon: Filter, name: "Filter" },
  { icon: Eye, name: "Eye" },
  { icon: EyeOff, name: "EyeOff" },
  { icon: Lock, name: "Lock" },
  { icon: Unlock, name: "Unlock" },
  { icon: Shield, name: "Shield" },
  { icon: AlertTriangle, name: "Alert" },
  { icon: HelpCircle, name: "Help" },
  { icon: Info, name: "Info" },
  { icon: Trash2, name: "Trash" },
];

export function getIconByName(name: string): LucideIcon | undefined {
  return availableIcons.find((item) => item.name === name)?.icon;
}