import {
  Activity,
  Beef,
  Beer,
  Bike,
  Book,
  Cake,
  CakeSlice,
  Calendar,
  Camera,
  Car,
  Cherry,
  Clock,
  Coffee,
  Cookie,
  CupSoda,
  Flame,
  Flag,
  Flower,
  Flower2,
  Gamepad2,
  Gift,
  GlassWater,
  Headphones,
  Heart,
  Home,
  IceCreamCone,
  Lamp,
  Lightbulb,
  type LucideIcon,
  MapPin,
  Megaphone,
  Mic,
  Music,
  Music2,
  Music3,
  Music4,
  Package,
  Palette,
  PartyPopper,
  Pizza,
  Popcorn,
  Sandwich,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Soup,
  Sparkle,
  Sparkles,
  Speaker,
  Star,
  Sun,
  Tent,
  Ticket,
  Timer,
  Trash2,
  TreePine,
  Trees,
  Trophy,
  Truck,
  UtensilsCrossed,
  Users,
  Utensils,
  Video,
  Wine,
  Zap,
} from "lucide-react";

export const availableIcons: { icon: LucideIcon; name: string }[] = [
  // Party & Celebration
  { icon: PartyPopper, name: "PartyPopper" },
  { icon: Gift, name: "Gift" },
  { icon: Cake, name: "Cake" },
  { icon: CakeSlice, name: "CakeSlice" },
  { icon: Sparkles, name: "Sparkles" },
  { icon: Sparkle, name: "Sparkle" },
  { icon: Star, name: "Star" },
  { icon: Trophy, name: "Trophy" },
  { icon: Heart, name: "Heart" },
  { icon: Ticket, name: "Ticket" },

  // Food & Drinks
  { icon: Utensils, name: "Utensils" },
  { icon: UtensilsCrossed, name: "UtensilsCrossed" },
  { icon: Pizza, name: "Pizza" },
  { icon: Sandwich, name: "Sandwich" },
  { icon: Soup, name: "Soup" },
  { icon: Cookie, name: "Cookie" },
  { icon: Popcorn, name: "Popcorn" },
  { icon: IceCreamCone, name: "IceCreamCone" },
  { icon: Cherry, name: "Cherry" },
  { icon: Coffee, name: "Coffee" },
  { icon: Beer, name: "Beer" },
  { icon: Wine, name: "Wine" },
  { icon: CupSoda, name: "CupSoda" },
  { icon: GlassWater, name: "GlassWater" },
  { icon: Beef, name: "Beef" },

  // Activities & Entertainment
  { icon: Music, name: "Music" },
  { icon: Music2, name: "Music2" },
  { icon: Music3, name: "Music3" },
  { icon: Music4, name: "Music4" },
  { icon: Headphones, name: "Headphones" },
  { icon: Mic, name: "Mic" },
  { icon: Speaker, name: "Speaker" },
  { icon: Gamepad2, name: "Gamepad" },
  { icon: Camera, name: "Camera" },
  { icon: Video, name: "Video" },
  { icon: Activity, name: "Activity" },
  { icon: Bike, name: "Bike" },
  { icon: Tent, name: "Tent" },
  { icon: Palette, name: "Palette" },
  { icon: Book, name: "Book" },

  // Setup & Logistics
  { icon: Users, name: "Users" },
  { icon: Package, name: "Package" },
  { icon: ShoppingCart, name: "ShoppingCart" },
  { icon: ShoppingBag, name: "ShoppingBag" },
  { icon: Truck, name: "Truck" },
  { icon: Car, name: "Car" },
  { icon: Home, name: "Home" },
  { icon: MapPin, name: "MapPin" },
  { icon: Clock, name: "Clock" },
  { icon: Timer, name: "Timer" },
  { icon: Calendar, name: "Calendar" },
  { icon: Megaphone, name: "Megaphone" },

  // Decorations & Ambiance
  { icon: Flower, name: "Flower" },
  { icon: Flower2, name: "Flower2" },
  { icon: Sun, name: "Sun" },
  { icon: Lightbulb, name: "Lightbulb" },
  { icon: Lamp, name: "Lamp" },
  { icon: Flame, name: "Flame" },
  { icon: Trees, name: "Trees" },
  { icon: TreePine, name: "TreePine" },
  { icon: Flag, name: "Flag" },
  { icon: Shirt, name: "Shirt" },

  // Utility
  { icon: Zap, name: "Zap" },
  { icon: Trash2, name: "Trash" },
];

export function getIconByName(name: string): LucideIcon | undefined {
  return availableIcons.find((item) => item.name === name)?.icon;
}

export function getIconName(icon: LucideIcon): string {
  const found = availableIcons.find((item) => item.icon === icon);
  return found?.name || "Star";
}
